# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
